-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 13:57:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pergi_kuliner
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_pergi_kuliner` ;

-- -----------------------------------------------------
-- Schema db_pergi_kuliner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pergi_kuliner` DEFAULT CHARACTER SET utf8 ;
USE `db_pergi_kuliner` ;

-- -----------------------------------------------------
-- Table `db_pergi_kuliner`.`tabled`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pergi_kuliner`.`tabled` ;

CREATE TABLE IF NOT EXISTS `db_pergi_kuliner`.`tabled` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `du` LONGTEXT NULL,
  `u` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pergi_kuliner`.`tablee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pergi_kuliner`.`tablee` ;

CREATE TABLE IF NOT EXISTS `db_pergi_kuliner`.`tablee` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `u` LONGTEXT NULL,
  `v` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pergi_kuliner`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pergi_kuliner`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `db_pergi_kuliner`.`restaurant` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(45) NULL,
  `price_min` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `price_max` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `address` VARCHAR(255) NULL,
  `open_day_from` VARCHAR(45) NULL,
  `open_day_to` VARCHAR(45) NULL,
  `open_time_from` TIME NULL,
  `open_time_to` TIME NULL,
  `phone` VARCHAR(45) NULL,
  `rating_overall` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_flavor` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_atmosphere` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_relevant` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_service` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_cleanliness` DECIMAL(14,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pergi_kuliner`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pergi_kuliner`.`payment` ;

CREATE TABLE IF NOT EXISTS `db_pergi_kuliner`.`payment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT UNSIGNED NOT NULL,
  `method` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_restaurant_id_idx`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_pergi_kuliner`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pergi_kuliner`.`facility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pergi_kuliner`.`facility` ;

CREATE TABLE IF NOT EXISTS `db_pergi_kuliner`.`facility` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT UNSIGNED NULL,
  `facility` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facility_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_facility_restaurant_id_idx`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_pergi_kuliner`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pergi_kuliner`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pergi_kuliner`.`review` ;

CREATE TABLE IF NOT EXISTS `db_pergi_kuliner`.`review` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `total_review` INT NOT NULL DEFAULT 0,
  `level` INT NOT NULL DEFAULT 0,
  `subject` VARCHAR(255) NULL,
  `rating_overall` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_flavor` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_atmosphere` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_relevant` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_service` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `rating_cleanliness` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `visit_date` DATE NULL,
  `price_from` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `price_to` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `review` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_restaurant_id_idx`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `db_pergi_kuliner`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pergi_kuliner`.`review_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pergi_kuliner`.`review_image` ;

CREATE TABLE IF NOT EXISTS `db_pergi_kuliner`.`review_image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `review_id` INT UNSIGNED NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_review_id_idx` (`review_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_review_id_idx`
    FOREIGN KEY (`review_id`)
    REFERENCES `db_pergi_kuliner`.`review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
